### ISSUE TITLE
Compiler crashes due to ^number under Clojure 1.8

### ISSUE THREAD

**Issue by halgari** [lbradstreet/instaparse-cljs#13]
There's some weird interaction with CLJ-1232 (http://dev.clojure.org/jira/browse/CLJ-1232) and this library. Since ^number is not a valid CLJ type hint, and `defn` is a macro that runs inside CLJ, we can't get this library to compile correctly for us under Clojure 1.8. The problem seems to be on this line: (https://github.com/clojure/clojure/blob/master/src/clj/clojure/core.clj#L247), the Clojure compiler will fail to compile if a tag doesn't exist.

**Comment by lbradstreet** [comment]
Thanks for the report @halgari 

Clojurescript used to type hint functions with ^number but it seems to be more complex in the latest version of clojurescript.

e.g. compare:
https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/core.cljc#L2414
to
https://github.com/clojure/clojurescript/blob/r3153/src/cljs/cljs/core.cljs#L283

I'm happy to remove the type hint, however the only places that we use it are very performance sensitive, so we need to make sure we get the solution right.

**Comment by halgari** [comment]
Sounds good, I also created a Clojure ticket for this (http://dev.clojure.org/jira/browse/CLJ-1863).

**Comment by lbradstreet** [comment]
I'm having some trouble getting tests to even get to this error with 1.8 and the latest clojurescript. I'll give it another try when I have some more time.

**Comment by aengelberg** [comment]
Instaparse-cljs seems to compile (and pass tests) under Clojure 1.8 and ClojureScript 1.8.40, so I'm going to close this ticket.
