### ISSUE TITLE
Transform don't touch  FlattenOnDemandVector

### ISSUE THREAD

**Issue by sadchi** [lbradstreet/instaparse-cljs#14]
After using parser i got a tree with some FlattenOnDemandVector. Nodes with such vectors are not processed with transform function. 
1. Let s say we have tree [:doc [:row "test string] #object[instaparse.auto-flatten-seq.FlattenOnDemandVector]]. FlattenOnDemandVector also contains row. 
2. Apply (intaparse/transform {:row str} tree) 
3. The first row is transformed, the second is not
   How to solve this?

**Comment by aengelberg** [comment]
Looks like FlattenOnDemandVector does not implement `ISequential`.

**Comment by sadchi** [comment]
I was able to make workaround by using clojure.walk/postwalk identity before applying transform. It would be better to do transform w/o extra steps.

**Comment by lbradstreet** [comment]
aengelberg is right. I will try to get this done when I have time. If anyone wants to provide a PR that would be good too.

**Comment by superstructor** [comment]
@lbradstreet #15 fixes this issue. Tested and working for me.

**Comment by lbradstreet** [comment]
Thank you @superstructor. I'll merge and cut you a new release

**Comment by lbradstreet** [comment]
Thank you again. Released in 1.4.1.1
