### ISSUE TITLE
Problem building instaparse-cljs

### ISSUE THREAD

**Issue by Grahack** [lbradstreet/instaparse-cljs#22]
Hi,  
I know about the deprecated status of this project, I just wanted to know if you knew what last version of ClojureScript could work with instaparse-cljs.

This is the error I get:

    Building ...
    Copying jar:file:/home/chri/.m2/repository/instaparse-cljs/instaparse-cljs/1.2.2-SNAPSHOT/instaparse-cljs-1.2.2-SNAPSHOT.jar!/instaparse/auto_flatten_seq.cljs to out/instapa
    rse/auto_flatten_seq.cljs
    Reading analysis cache for jar:file:/home/chri/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/core.cljs
    Compiling out/instaparse/auto_flatten_seq.cljs
    clojure.lang.ExceptionInfo: failed compiling file:out/instaparse/auto_flatten_seq.cljs {:file #object[java.io.File 0x68fefa2c "out/instaparse/auto_flatten_seq.cljs"]}
    ...
    Caused by: clojure.lang.ExceptionInfo: No such namespace: cljs.core.PersistentVector, could not locate cljs/core/PersistentVector.cljs, cljs/core/PersistentVector.cljc, or JavaScript source providing "cljs.core.PersistentVector" in file out/instaparse/auto_flatten_seq.cljs {:tag :cljs/analysis-error}

I use 1.2.2 because `[com.lucasbradstreet/instaparse-cljs "1.4.1.2"]` doesn't seem to be available, which I consider normal if the project is deprecated.

Thanks.

**Comment by lbradstreet** [comment]
Hi. The port was merged upstream so cljs is now supported by https://github.com/Engelberg/instaparse. I will archive the project now that it's possible to do so in github.
