### ISSUE TITLE
Small formatting bug in "__ rule occurs on right-hand side..." error

### ISSUE THREAD

**Issue by aengelberg** [lbradstreet/instaparse-cljs#3]
In [this](https://github.com/lbradstreet/instaparse-cljs/blob/master/src/cljs/instaparse/cfg.cljs#L238) line, the string to be appended should start with a space. Currently I'm getting errors like:

```
my-ruleoccurs on the right-hand side of your grammar, but not on the left
```

(Note the lack of space between `my-rule` and `occurs`)

In the clj code, the error would be constructed with a call to `format`, and the space is included, but it must have been lost during the conversion to using str in cljs.

Thanks for your awesome work on the Clojurescript port!
--Alex

**Comment by lbradstreet** [comment]
Thanks for the report! I'll get a release out ASAP. Clojurescript doesn't have a format function so I obviously made a bit of a mistake there.

**Comment by lbradstreet** [comment]
Fixed in master
